version: "3.9"
services:
  web:
    # volumes:
    #   - ~/apochat/:/var/app
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0','1']
            capabilities: [gpu]
